---
- hosts: localhost
  connection: local

  tasks:

    - name: Check if EPEL repository installed 
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epelrepo

    - name: Add required repostiories
      command:
        cmd: dnf config-manager --add-repo "{{ item }}"  
      become: true
      loop:
          - https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo
          - https://cli.github.com/packages/rpm/gh-cli.repo
          - https://gist.githubusercontent.com/webgtx/c1f68f5a063c3c10e9539b9f4645c890/raw/aa9d68399817a95d4755cfd5e224427028b9d7fe/kubernetes.repo

    - name: Ensure in useful packages for my daily workflow
      package:
        name: 
          - zsh
          - ruby
          - bat
          - htop
          - gh
          - chromium
          - irssi
          - clang
          - podman
          - podman-tui
          - podman-compose
          - proxychains-ng
          - openvpn
          - NetworkManager-openvpn
          - gnome-tweaks
          - wireguard-tools
          - tor
          - tailscale
          - keepassxc
          - kubectl
      become: true
      when: epelrepo.stat.exists
    
