--- 
- hosts: localhost
  connection: local
  
  tasks:
    - name: Resolve requirements
      become: true 
      package:
        name:
          - i3-gaps
          - i3lock
          - i3status
          - dmenu
          - nitrogen
          - picom
          - alacritty
        state: present
