---
- hosts: localhost
  connection: local
  vars_files: "../../vars/main.yml"

  tasks:
    - name: Import dot configs to the repostiory
      synchronize:
        src: "~/.config/{{ item }}"
        dest: "../../configs"
        recursive: true
      loop: "{{ dots }}"
