---
- hosts: localhost 
  connection: local
  vars_files: "../../vars/main.yml"

  tasks:
    - name: Copy all shellrc files to the repostiory
      copy:
        src: "~/.{{ item }}rc"
        dest: "../../rcs/{{ item }}rc"
      loop: "{{ shells }}"
