--- 
- hosts: localhost
  connection: local
  
  # I don't install packages that are pre-installed in fedora sway spin
  tasks:
    - name: Resolve requirements
      become: true 
      package:
        name:
          - wl-clipboard
          - grim
        state: present
