# .bashrc

# cat $HOME/.local/share/assets/ascii/eyes.ascii
# echo "	> Welcome back, $USER."

# Aliases
alias dev="toolbox run --container dev zsh"
alias hack="toolbox run --container blackarch fish"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
export DEVRM="$HOME/Desktop/devroom/"

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc
