export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="/usr/bin/vim"
export ZSH_THEME="clean"
export GEMINI_API_KEY=$(cat ~/Documents/api/google.gemini.key)
export GEMINI_MODEL="gemini-1.5-flash"

clrs() {
  for x in {0..8}; do 
    for i in {30..37}; do 
      for a in {40..47}; do 
        echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "
      done
      echo
    done
  done
  echo ""
}

plugins=(

  # Tools
  git
  ansible
  terraform
  gcloud
  python
  ruby
  kubectl
  minikube
  helm
  dnf
  docker

  # Clouds
  doctl
  aws
  azure

  # Usability
  vi-mode

)

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias irssi="podman run -it --rm -v $HOME/.irssi:/home/user/.irssi:z -v /etc/localtime:/etc/localtime:ro irssi:alpine irssi"
alias rr=ranger
alias s=sudo
alias wttr="curl wttr.in"

odir () {
  tmp=$(mktemp)
  ranger --choosedir=$tmp
  dir=$(cat $tmp)
  [ -d $dir ] && [ $dir != $PWD ] && cd $dir
}

bindkey -s "^o" "odir\n"
